### ISSUE TITLE
View 

### ISSUE THREAD

**Issue by kutszy** [chrisbevan/skin.pellucid#24]
Hi is tears any chance to change the view for certain directories in the addons? One of the addon I'm using changed the view from list to poster(?) and I can't find the way to change it  back.

**Comment by arthurvaverko** [comment]
+1

**Comment by arthurvaverko** [comment]
I'd be glad to make it happen .. its just I'm a bit new to kodi skins.
i have a fair grasp on coding and i do understand the basics .. be glad if someone couls point me in a general direction to add an option switching view types..
i have tried just adding a button for Content.NextViewType but this did not work

**Comment by chrisbevan** [comment]
The views in Pellucid are hard coded, so that approach won't work.

If you can let me know which add-ons are misbehaving I will look into it
and suggest the best way forward.

**Comment by arthurvaverko** [comment]
Covenant is misbehaving.
Its tv shows and moview are okay .. But the seasons and episods are displayed using a list which is boring.. The poster rail for seasons is much better .. And episodes should be using the episodes view..

**Comment by arthurvaverko** [comment]
I saw the expression hardcoding the visible tag of each view .. 

The expresions are in includes.xml 
. i juat dont have enugth knowladge to fix them

**Comment by chrisbevan** [comment]
Yes, you're looking in the right places.

However, you're opening Pandora's box. I have discussed this at length on
the forums so won't repeat here, but - in short - add-ons are bandit
country. There is no quality control, so it's a total mess.

Allowing poster view for movies and TV shows is pushing it as it is. For
all else, the list view is the only safe option. Sorry - Kodi is built for
local content, so local content will always deliver a better user
experience.

Finally, covenant is obviously illegal, so for the sake of Kodi in general,
i'm very reluctant to support it!



On 20 Oct 2017 5:05 a.m., "Arthur Vaverko" <notifications@github.com> wrote:

I saw the expression hardcoding the visible tag of each view ..

The expresions are in includes.xml
. i juat dont have enugth knowladge to fix them

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/chrisbevan/skin.pellucid/issues/24#issuecomment-338093661>,
or mute the thread

**Comment by arthurvaverko** [comment]
Understood ... I can approciat that... :)
Thnx ..

**Comment by earithramir** [comment]
Anyway to change the default view to list view?

My CrunchyRoll (legal by the way!) addon is not really usable like this. 
Can share (publicly) the source of that plugin as it is beta and not yet publicly available. (a payed subscription is needed to test it) Could u point me in the right direction?
