### ISSUE TITLE
home screen redesign

### ISSUE THREAD

**Issue by hotdog3388** [chrisbevan/skin.pellucid#31]
would have posted in the forum but its down. 
While I love the skin in general, I'm not a fan of the new home screen redesign. any way we could get an option to switch back to the old view or hide the menu options in a list off to the side like before? 
The buttons in the middle of the screen hide the beautiful backgrounds and just look cluttered to me. In addition, the weather doesn't show up on the home screen. 
Thanks man

**Comment by Basil-4** [comment]
Totally agree. Awesome minimalistic homescreen with a slideshow, time and weather was the main reason for me to use Pellucid. It looked so nice, that I kept my TV on all the time while listening to music in the background. Now it doesn't look like a thing to look at. An option for turning previous version back would be great.

**Comment by chrisbevan** [comment]
Thanks both for you comments. 

I am going to stand by the new menu design, but understand your point of view. What I will do is add a timed transition that will hide the menu items / move the clock etc to the bottom, with an easy shortcut to do the same thing immediately. 

Happy to reinstate the weather also. I'll update this post when the work is complete if you both want to update from Github instead of waiting for an official update.

FYI, this will probably be the last update for Krypton. I'll be moving on to Leia shortly. 

Thanks for your continued support, it is much appreciated.

**Comment by chrisbevan** [comment]
Addendum... Is having the weather on the homescreen really critical? It's proving to be a total pain in the a$%e..

**Comment by hotdog3388** [comment]
haha it's not the biggest issue since i have a weather widget on my phone, it was just a nice bonus. having a clean background and being able to hide the menu items is the biggest priority for me personally

**Comment by chrisbevan** [comment]
OK, autohide (20 secs) and menu toggle added on latest GIT if you want to give it a try.

**Comment by Basil-4** [comment]
Much better. But anyway, that's not the reason why I loved Pellucid. :-( Could you please tell me how to rollback to the previous version with just time, weather and a song name in the right lower corner without all that extra buttons and icons? I couldn't find a way. Thank you.

**Comment by chrisbevan** [comment]
Of course. You can downgrade to 1.2.4 by downloading from an earlier commit:
https://github.com/chrisbevan/skin.pellucid/tree/22b09d872fa41aa017d913abec0e33ceabb2e9d5
