### ISSUE TITLE
Font and Icon very small using iagl

### ISSUE THREAD

**Issue by robmcc1983** [chrisbevan/skin.pellucid#49]
Hi,
Love your skin been using for a while now but have found a small issue.
When I use iagl, the screen where you select launch, trailer download etc.
The icons in the box are very small and so is the font.
Thanks
Rob

**Comment by chrisbevan** [comment]
Hi Rob,

Thanks for reporting. IAGL = Internet archive game launcher?

Chris.

**Comment by robmcc1983** [comment]
Yeah that's the one :) just added it to my setup and noticed this.

Thanks

**Comment by chrisbevan** [comment]
Thanks. I'll take a look. I won't be reskinning IAGL to fit the general Pellucid UI as it's a dependency I cannot control, but there may be a fix I can make that renders it at least readable!

Here's hoping the Kodi folks develop the internal gaming library sooner rather than later :-)

Chris.

**Comment by robmcc1983** [comment]
It shows correctly on kodi default skin, just not yours so hopefully you can do something :)
Thanks

**Comment by robmcc1983** [comment]
![screenshot_20190208-122232](https://user-images.githubusercontent.com/19917296/52478301-d6ca8580-2b9c-11e9-8365-c3aaae0dc8ff.jpg)

![screenshot_20190208-122636](https://user-images.githubusercontent.com/19917296/52478308-de8a2a00-2b9c-11e9-9539-e88e44e0d524.jpg)

This is the difference between Kodi default skin and yours.
Hope this helps
Thanks

**Comment by chrisbevan** [comment]
Thanks. Addons are a pain in my arse. The problem is that they build the things for the default skin and don't think about font support. There's nothing I can do about this other than to provide my own skin files for the addon. 

The amount of work involved to do that is extensive, and I don't have the time or inclination to do it - particularly given that gaming library support in Kodi will inevitably render this addon obsolete. Sorry about that, I hope you can understand my position.
