### ISSUE TITLE
add arial front

### ISSUE THREAD

**Issue by JQXX** [chrisbevan/skin.pellucid#54]
Hi!
Amzing work!Love it!

Is it possible support arial front that I can display chinese.
Thanks!

**Comment by chrisbevan** [comment]
Thanks!

I'll look into it for you. Arial will probably look rubbish though. If you want to replace the fonts quickly, you could replace the current Roboto fonts with Noto (just keep the same weights and filenames)

**Comment by PhilippMundhenk** [comment]
first of all: Awesome skin! Great work! Love it! Thank you! And would love to use it...but:
I have some Chinese albums, main system is set to English though. Just replacing Roboto with Noto would not help me, right? I would need to merge Roboto and Noto CJK TC (in my case) to be able to show both. Or am I missing something here?

I tried by adding a new fontset for noto, using noto identical to roboto (and also noto instead of robot_slab). Looks are slightly different, some bold where it wasn't with roboto, but most importantly: Chinese characters are still not shown.

**Comment by chrisbevan** [comment]
Thanks!

I'm not 100%, but looking at Google Fonts, there's a 'Noto TC' that clearly has latin glyphs as well as chinese. That **should** work: https://fonts.google.com/specimen/Noto+Sans+TC?query=noto&subset=chinese-traditional#standard-styles

Merging roboto and noto CJK probably won't work.. Noto CJK is (as far as I know) maxed out on glyphs. 

Failing all that, i've just added arial support in the latest commit.

**Comment by truthfulie** [comment]
Thanks for the update, I asked for this on Kodi forum and nice to see it implemented. I do have a question though. The reason why I even wanted Ariel support was because my parents watch their shows with PsuedoTV via Kodi and Korean characters are broken with Roboto and Heebo. Ariel does seem to fix this for the _most part_. I don't know what is causing this, maybe font isn't assigned to something? But PsuedoTV programing guide still has broken Korean characters.

I modded the skin on my HTPC with a Korean font and that seems to work fine, but I don't think I can do the same with an Android box. Would like to know if there is a workaround. Thanks!

**Comment by chrisbevan** [comment]
Hi Truthfulie
You should be able to access the skin on an android device at Android/data/org.xbmc.kodi/files/.kodi/addons/skin.pellucid. You could apply your mod there, but future updates to the skin will likely overwrite it.

Alternatively, what was the Korean font that you used? If it's on a free-to-use license and doesn't involve any other skin modifications, I'd be happy to include it in the official skin.

**Comment by truthfulie** [comment]
Yes, I wanted to install a skin that won't be overwritten in case of update. I used Nanum Gothic to mod my PC client. Can be found on Google Fonts. But there are only three styles available. It may be better to use Noto Sans KR, also available on Google Fonts, which 6 styles.

**Comment by PhilippMundhenk** [comment]
I tried Noto TC, after converting from otf to ttf, I end up with rectangular boxes only. Might be that I screwed up the conversion. I will learn about fonts a bit more and then try that again.

**Comment by chrisbevan** [comment]
OK... I've just added NotoCJK and it appears to display TC and Korean characters correctly. Give that a go.

Note that some strings are custom to the skin and will therefore remain in English until a translation is provided. If either of you would be willing to help out in that regard, I would be most grateful.

**Comment by truthfulie** [comment]
Thanks! I'll test out the updated one tonight. And sure, I can help out with the translation. Let me know what you need!

**Comment by chrisbevan** [comment]
Thanks - much appreciated. Feel free to add comments to the doc where extra context is needed and I'll help out where I can.
